ClothingShop/Controllers/LoginController.cs
using ClothingShop.DTO;
using ClothingShop.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ClothingShop.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public LoginController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(AppUserLogin appUserLogin)
        {
            var result = await _signInManager.PasswordSignInAsync(appUserLogin.Username, appUserLogin.Password, false, true);
            if (result.Succeeded)
            {
                var user = await _userManager.FindByNameAsync(appUserLogin.Username);
                if (user.EmailConfirmed == true)
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }
    }
}

ClothingShop/Controllers/RegisterController.cs
using ClothingShop.DTO;
using ClothingShop.Extensions;
using ClothingShop.Models;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MimeKit;

namespace ClothingShop.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IEmailService _emailService;
        private readonly UserManager<AppUser> _userManager;
        public RegisterController(UserManager<AppUser> userManager, IEmailService emailService)
        {
            _emailService = emailService;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(AppUserRegister appUserRegister)
        {
            if (ModelState.IsValid)
            {
                Random random=new Random();
                int code;
                code= random.Next(100000, 1000000);
                AppUser appUser = new AppUser()
                {
                    UserName = appUserRegister.Username,
                    Email = appUserRegister.Email,
                    Name = appUserRegister.Name,
                    Surname = appUserRegister.Surname,
                    ConfirmCode = code
                };
                var result= await _userManager.CreateAsync(appUser,appUserRegister.Password);
                if (result.Succeeded)
                {
                    await _emailService.SendEmailAsync(appUser.Email,"Confirm Email",$"{code}");
                    

                    TempData["mail"] = appUserRegister.Email;
                    return RedirectToAction("ConfirmMail", "ConfirmMail");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }

            return View(appUserRegister);
        }
    }
}

ClothingShop/Views/Register/Register.cshtml
@using ClothingShop.DTO
@model AppUserRegister
<div class="mb-4 pb-4"></div>
<section class="login-register container">
    <ul class="nav nav-tabs mb-5" id="login_register">
        <li class="nav-item" role="presentation">
            <a class="nav-link" asp-controller="Login" asp-action="Login">Login</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" asp-controller="Register" asp-action="Register">Register</a>
        </li>
    </ul>
    <div class="tab-content pt-2" id="login_register_tab_content">
   
        <div class="fade show active">
            <div class="register-form">
                <form asp-action="Register" method="post" class="needs-validation" novalidate>
                    <div class="form-floating mb-3">
                        <input asp-for="Username" type="text" class="form-control form-control_gray" id="customerNameRegisterInput" placeholder="Username" required>
                        <label asp-for="Username">Username</label>
                    </div>

                    <div class="form-floating mb-3">
                        <input asp-for="Name" type="text" class="form-control form-control_gray" id="customerNameRegisterInput" placeholder="Name" required>
                        <label asp-for="Name">Name</label>
                    </div>

                    <div class="form-floating mb-3">
                        <input asp-for="Surname" type="text" class="form-control form-control_gray" id="customerNameRegisterInput" placeholder="Surname" required>
                        <label for="customerNameRegisterInput">Surname</label>
                    </div>

                    <div class="form-floating mb-3">
                        <input asp-for="Email" type="email" class="form-control form-control_gray" id="customerEmailRegisterInput" placeholder="Email address *" required>
                        <label for="customerEmailRegisterInput">Email address *</label>
                    </div>

                    <div class="form-floating mb-3">
                        <input asp-for="Password" type="password" class="form-control form-control_gray" id="customerPasswodRegisterInput" placeholder="Password *" required>
                        <label for="customerPasswodRegisterInput">Password *</label>
                    </div>
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="d-flex align-items-center mb-3 pb-2">
                        <p class="m-0">Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy.</p>
                    </div>

                    <button class="btn btn-primary w-100 text-uppercase" type="submit">Register</button>
                </form>
            </div>
        </div>
    </div>
</section>